package com.example.shortener.feature.link.controller;
import com.example.shortener.feature.link.dto.LinkForm; import com.example.shortener.feature.link.service.ShortLinkService; import jakarta.validation.Valid; import org.springframework.data.domain.PageRequest; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.validation.BindingResult; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.support.RedirectAttributes;
@Controller @RequestMapping("/dashboard/links") public class LinkController { private final ShortLinkService service; public LinkController(ShortLinkService s){service=s;}
@GetMapping public String list(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size,Authentication a,Model m){m.addAttribute("links",service.findByUser(a.getName(),PageRequest.of(page,size)));m.addAttribute("form",new LinkForm());return "link/list";}
@PostMapping public String create(@Valid @ModelAttribute("form")LinkForm f,BindingResult b,Authentication a,RedirectAttributes r,Model m){if(b.hasErrors()){m.addAttribute("links",service.findByUser(a.getName(),PageRequest.of(0,10)));return "link/list";}service.create(a.getName(),f);r.addFlashAttribute("success","Link created");return "redirect:/dashboard/links";}
@GetMapping("/{id}/edit") public String edit(@PathVariable Long id,Authentication a,Model m){var l=service.owned(a.getName(),id);m.addAttribute("link",l);m.addAttribute("form",new LinkForm(l.getOriginalUrl(),l.getTags().stream().map(t->t.getName()).sorted().reduce((x,y)->x+","+y).orElse("")));return "link/edit";}
@PostMapping("/{id}") public String update(@PathVariable Long id,@Valid @ModelAttribute("form")LinkForm f,BindingResult b,Authentication a,RedirectAttributes r,Model m){if(b.hasErrors()){m.addAttribute("link",service.owned(a.getName(),id));return "link/edit";}service.update(a.getName(),id,f);r.addFlashAttribute("success","Link updated");return "redirect:/dashboard/links";}
@PostMapping("/{id}/delete") public String delete(@PathVariable Long id,Authentication a,RedirectAttributes r){service.delete(a.getName(),id);r.addFlashAttribute("success","Link deleted");return "redirect:/dashboard/links";}
@GetMapping("/{id}/stats") public String stats(@PathVariable Long id,@RequestParam(defaultValue="0")int page,Authentication a,Model m){m.addAttribute("link",service.owned(a.getName(),id));m.addAttribute("clicks",service.clickPage(id,PageRequest.of(page,20)));return "link/stats";}}
